name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - run: cargo build --verbose

      - run: cargo install cargo-tarpaulin
      - run: cargo install cargo-audit
      - run: rustup component add clippy
      - run: rustup component add rustfmt

      - run: cargo test --verbose
      - run: cargo tarpaulin --ignore-tests
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo audit
